#!/bin/sh

set -e

case "${1}" in
	remove)
		if [ -e /etc/default/extlinux ]
		then
			. /etc/default/extlinux

			if [ "${EXTLINUX_THEME}" = "netrunner" ]
			then
				sed -i -e 's|^ *EXTLINUX_THEME=.*|EXTLINUX_THEME=""|' /etc/default/extlinux

				extlinux-update
			fi
		fi
		;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
